feat: header
akimoveduard/itmo-landing pull request #13
Opened 2022-03-30 21:23 UTC by zvzyung

2022-03-30 22:05 UTC, StMelik commented on index.html
> +      <div class="header__menu">
Здесь лучше использовать тег nav

2022-03-30 22:07 UTC, StMelik commented on index.html
> +        <button class="header__menu-tab header__menu-tab_active">О нас</button>
Сделать списком.
Также нужно использовать ссылки для перехода к разделам сайта по якорям

2022-03-30 22:09 UTC, StMelik commented on index.html
> +      <img src="images/logo.png" alt="Логотип сайта" class="header__logo">
Класс лучше поставить первым.

2022-03-30 22:14 UTC, StMelik commented on blocks/header/header.css
> +  margin: 0 auto;
Это лишнее. Да и margin auto без явно заданной ширины не отработает.

2022-03-30 22:23 UTC, StMelik commented on blocks/header/__container/header__container.css
> +  width: 77%;
Почему 77? при 100 тоже отлично работает))

2022-03-30 22:25 UTC, StMelik commented on blocks/header/__menu-tab/_active/header__menu-tab_active.css
> +  ;
;)

2022-03-30 22:40 UTC, StMelik requested changes
Необходимо решить конфликт

Посмотреть замечания

2022-03-31 06:01 UTC, akimoveduard commented on blocks/header/__container/header__container.css
> +  width: 77%;
Я немного не согласен с шириной в процентах. Ее трудно контролировать. У хедера максимальная ширина с падингами 1440 пикселей. То есть задаем ему width 100%, padding: 13px 165px; и он встанет, как по макету.

2022-03-31 06:16 UTC, akimoveduard commented
Мансур, тебе нужно внести исправления согласно ревью.

2022-03-31 06:16 UTC, closed without merging

2022-03-31 11:48 UTC, zvzyung commented on blocks/header/header.css
> +  margin: 0 auto;
После изменений в коде, к сожалению без margin 0 auto не обойтись