hotfix: исправить header
akimoveduard/itmo-landing pull request #18
Opened 2022-03-31 12:56 UTC by zvzyung

2022-03-31 14:34 UTC, StMelik commented on blocks/header/header.css
> +  max-width: 1440px;
Не нужно ограничивать ширину. При расширении более 1440px появятся "уши".
Для ограничения ширины контента и его центрирования лучше сделать обёртку

2022-03-31 14:41 UTC, StMelik commented on blocks/header/header.css
> +  min-height: 80px;
Можно убрать. Ширина у тебя выставляется падингами

2022-03-31 14:41 UTC, StMelik commented on blocks/header/__container/header__container.css
> +  padding: 13px 165px;
вертикальный падинг делает необходимую ширину, а горизонтальный можно убрать

2022-03-31 14:42 UTC, StMelik commented on blocks/header/header.css
> +  display: flex;
Лишнее

2022-03-31 14:50 UTC, StMelik commented on blocks/header/__menu/header__menu.css
> +  margin-bottom: 2px;
Это зачем?!

2022-03-31 14:57 UTC, StMelik commented on blocks/header/__menu-item/header__menu-item.css
> +  min-height: 44px;
Здесь можно сделать через падинг

2022-03-31 14:58 UTC, StMelik commented on blocks/header/__menu-item/_active/header__menu-item_active.css
> +  ;
;)

2022-03-31 15:01 UTC, StMelik commented on blocks/header/__menu-item-link/header__menu-item-link.css
> +  margin: auto;
Без этого тоже работает

2022-03-31 15:01 UTC, StMelik commented on blocks/header/__menu-item-link/header__menu-item-link.css
> +  font-style: normal;
Он по дефолту normal

2022-03-31 15:01 UTC, StMelik commented on blocks/header/__menu-item-link/header__menu-item-link.css
> +  font-weight: 400;
Тоже лишнее - значение по дефолту

2022-03-31 15:04 UTC, StMelik commented on blocks/header/__menu-list/header__menu-list.css
> +  width: 825px;
Не очень нравится эта ширина, попробуй другую реализацию.
Если ничего не получится пусть пока что остается так

2022-03-31 15:04 UTC, StMelik requested changes
На расширении более 1440 появляются уши

2022-03-31 15:35 UTC, akimoveduard commented
Поправить в соответствии с замечаниями Стаса.

2022-03-31 15:35 UTC, closed without merging

2022-04-01 12:33 UTC, zvzyung commented on blocks/header/__menu-list/header__menu-list.css
> +  width: 825px;
К сожалению у меня не получилось по другому реализовать