Feat/education
akimoveduard/itmo-landing pull request #21
Opened 2022-04-01 07:06 UTC by akimoveduard

2022-04-01 14:38 UTC, StMelik commented on blocks/education/__card-text/education__card-text.css
> +  justify-content: space-between;
Не очень хорошее решение. Если пунктов в списке станет меньше, они начнут выравниваться по центру.

2022-04-01 14:40 UTC, StMelik commented on blocks/education/__card-text/education__card-text.css
> +  display: flex;
Да и вообще, зачем здесь флексы? :)

2022-04-01 14:48 UTC, StMelik commented on blocks/education/__card/education__card.css
> +  padding: 30px;
нижний паддинг 35пх

2022-04-01 14:50 UTC, StMelik commented on blocks/education/__cards-wrapper/education__cards-wrapper.css
> +  margin: 60px auto 35px auto;
60 а 35

2022-04-01 14:50 UTC, StMelik commented on blocks/education/__tab-bar/education__tab-bar.css
> +  padding: 0 0 0px 0;
0

2022-04-01 14:51 UTC, StMelik commented on blocks/education/__tab-bar/education__tab-bar.css
> +  flex-direction: row;
дефолтное значение

2022-04-01 14:56 UTC, StMelik commented on blocks/education/__card-footer/education__card-footer.css
> +  justify-self: baseline;
-

2022-04-01 14:57 UTC, StMelik commented on blocks/education/__card-link/education__card-link.css
> +  transition: 1.3 ease;
???

2022-04-01 15:07 UTC, StMelik commented on blocks/education/__card-link/education__card-link.css
> +  top: 0.45rem;
Не самый надежный способ выровнять по центру, да и значение подбирать нужно :)
Можно делать -  top 50%; transform translateY(-50%).

2022-04-01 15:10 UTC, StMelik commented on blocks/education/__tab/education__tab.css
> +  transform: translateX(15px);
Можно было и родительскому контейнеру задать бордер :)

2022-04-01 15:21 UTC, StMelik commented on js/tabs.js
> +    barTabs.forEach((tab) => {
Думаю в такой простой задаче не нужен цикл в цикле ;)

2022-04-01 15:22 UTC, StMelik requested changes
- Активную кнопку лучше сделать белой

- Думаю круче выглядело бы если бы кнопка переползала со стороны в сторону. Ну это уже вкусовщина, ради практики можешь попробовать реализовать ;)

- Лишняя картинка в файлах

- Считаю, что анимация слишком быстрая

- JS сложновато читать. Разбей его по функциям. Ну и от цикла в цикле думаю стоит избавиться.

- Удалить консоль логи

2022-04-01 15:24 UTC, StMelik commented
Пулл реквест не закрывай

2022-04-01 17:21 UTC, rutaizm commented on blocks/education/__card-header/education__card-header.css
> +  padding: 0 0 10px 0;
Можно сократить запись

2022-04-01 17:24 UTC, rutaizm commented on blocks/education/__card-list/education__card-list.css
> +  margin: 0 0 10px 0;
можно сократить запись

2022-04-01 17:26 UTC, rutaizm commented on blocks/education/__cards-wrapper/education__cards-wrapper.css
> +  margin: 60px auto 35px auto;
и тут сократить можно написание

2022-04-01 17:29 UTC, rutaizm commented on blocks/education/__tab/_active/education__tab_active.css
> +  z-index: 5;
почему 5?

2022-04-02 05:04 UTC, akimoveduard commented on blocks/education/__tab/_active/education__tab_active.css
> +  z-index: 5;
Там два таба и они как бы накладываются друг на друга. Одному дал 5, другому 10. Привычка такая появилась, а вдруг, мол, еще что-то появится, кому будет нужен z-index.

2022-04-02 05:09 UTC, akimoveduard commented on blocks/education/__card-text/education__card-text.css
> +  display: flex;
> Да и вообще, зачем здесь флексы? :)

Моя любимая невнимательность. :)

2022-04-02 07:17 UTC, akimoveduard commented on blocks/education/__card-text/education__card-text.css
> +  display: flex;
> Да и вообще, зачем здесь флексы? :)

Здесь flex, чтобы прибить ссылку к нижней части карточки. Хотя в макете это никак не отражено, но мне кажется, что оно так предполагается. Правда это видно только если список не очень длинный. Пусть будет так.

2022-04-02 07:23 UTC, akimoveduard commented on blocks/education/__card/education__card.css
> +  padding: 30px;
Вроде по макету все 30
![2022-04-02_10-23-02](https://user-images.githubusercontent.com/95487679/161372009-9ba306e9-2da8-4d2c-abd1-552840e6f3ce.png)

2022-04-02 07:24 UTC, akimoveduard commented on blocks/education/__cards-wrapper/education__cards-wrapper.css
> +  margin: 60px auto 35px auto;
Да, согласен. Я на пр1 сократил так, мне ревьюер по рукам стукнула. С тех пор вот так вот...

2022-04-02 07:26 UTC, akimoveduard commented on blocks/education/__tab-bar/education__tab-bar.css
> +  padding: 0 0 0px 0;
> 0

Ага, это я экспериментировал и забыл удалить. Невнимательность -- мой конёк. :))

2022-04-02 09:27 UTC, StMelik commented on blocks/education/__card/education__card.css
> +  padding: 30px;
![image](https://user-images.githubusercontent.com/93302874/161376887-94c78b1e-20c7-4a57-969d-a8dafcc774ac.png)

2022-04-02 09:33 UTC, StMelik commented on blocks/education/__card/education__card.css
> +  padding: 30px;
У картинки 35 внизу по макету, у тебя 30. И общая высота у тебя как раз 5 пикселей потерялись. Возможно косяк макета.

2022-04-02 09:35 UTC, StMelik commented on blocks/education/__card-text/education__card-text.css
> +  display: flex;
Ок пусть будет так) Еще прибить к низу, да и к чему угодно, можно с помощью margin: auto

2022-04-02 13:15 UTC, akimoveduard commented
> * Активную кнопку лучше сделать белой
Да, точно! Я еще удивился почему они так сделали, а это просто я не так понял.

> * Думаю круче выглядело бы если бы кнопка переползала со стороны в сторону. Ну это уже вкусовщина, ради практики можешь попробовать реализовать ;)
Пока даже идей нет, как такое провернуть.

> * Лишняя картинка в файлах
Удалил.

> * Считаю, что анимация слишком быстрая
Добавил вместо .3s .5s.

> * JS сложновато читать. Разбей его по функциям. Ну и от цикла в цикле думаю стоит избавиться.
В JS я пока слабоват. От цикла избавился. По функциям разбил, но не уверен, что теперь читать легче.

> * Удалить консоль логи
О господи, опять я их оставил. :((

2022-04-02 14:23 UTC, merged