feat: lab 1итерация
akimoveduard/itmo-landing pull request #22
Opened 2022-04-01 07:41 UTC by akimoveduard

2022-04-01 17:35 UTC, rutaizm commented on blocks/lab/__card-button/lab__card-button.css
> +  cursor: pointer;
cursor: pointer  в состоянии hover не нужен - он уже есть в обычном состоянии. Где-то надо убрать лишний

2022-04-01 17:36 UTC, rutaizm commented on blocks/lab/__card-button/lab__card-button.css
>    font-size: 0.875rem;
Может старые добрые пиксели?

2022-04-01 17:44 UTC, rutaizm commented on blocks/lab/__cards/lab__cards.css
>    display: grid;
повтор

2022-04-01 18:04 UTC, rutaizm commented on blocks/lab/__card-paragraph/lab__card-paragraph.css
> +}
https://disk.yandex.ru/d/UYEwose3qzEnwA
тут очень сильное расхождение с оригиналом - возможно нужен отступ для текста

2022-04-02 13:08 UTC, StMelik commented on index.html
> +      <h1 class="section__title">Industrial AI Research Lab</h1>
h2

2022-04-02 13:09 UTC, StMelik commented on index.html
> +          <h2 class="lab__title">Центр национальной технологической инициативы (НТИ), получивший государственную поддержку
Здесь подойдет <p></p>

2022-04-02 13:12 UTC, StMelik commented on index.html
> +            <img class="lab__icon" src="./images/moleculer.png" alt="молекула">
Лучше на brfore сделать

2022-04-02 13:14 UTC, StMelik commented on index.html
> +          <button class="lab__card-button">Подробнее</button>
Здесь лучше ссылкой сделать. Скорее всего будет переход на другую страницу

2022-04-02 13:18 UTC, StMelik commented on blocks/lab/lab.css
> +  margin: 0 165px 0 129px;
Не выровняет по центру! margin 0 auto

2022-04-02 13:27 UTC, StMelik commented on blocks/lab/lab.css
> +.lab {
макс ширина 1110пх

2022-04-02 13:30 UTC, AdelinaKh commented on blocks/lab/lab.css
> +  margin: 0 165px 0 129px;
на макете такие значения. мне тогда нужно задать max-width и margin 0 auto?

2022-04-02 13:31 UTC, StMelik commented on blocks/lab/__description/lab__description.css
> +  max-width: 576px;
540

2022-04-02 13:33 UTC, StMelik commented on blocks/lab/__photos/lab__photos.css
> +  flex-direction: row;
Дефолтное значение

2022-04-02 13:42 UTC, StMelik commented on blocks/lab/__paragraph/lab__paragraph.css
> +  flex-direction: row;
дефолтное значение

2022-04-02 13:42 UTC, StMelik requested changes
- Значок молекулы сделать через before

- Ширина блока не совпадает с макетом

- Сделать анимацию плавной

2022-04-02 16:36 UTC, StMelik commented on blocks/lab/lab.css
> +  margin: 0 165px 0 129px;
> на макете такие значения. мне тогда нужно задать max-width и margin 0 auto?

На макете оно стоит по центру. И тогда не 0 165 0 129, а 0 165 0, но тогда на разрешение экрана больше 1440, контент не будет выравниваться по центру. margin 0 auto решит эту проблему, и контент на любом разрешение экрана будет по центру

2022-04-02 19:34 UTC, AdelinaKh commented on blocks/lab/lab.css
> +.lab {
https://disk.yandex.ru/i/BsTRTOu02Yyq1w
посмотри, пожалуйста) если устанавливаю такую ширину, то заголовок выравнивается неправильно(по центру 1110пх, а на макете он выровнен по ширине 1146пх )
https://disk.yandex.ru/i/Z2R_erbqosrbLw

2022-04-05 21:01 UTC, StMelik reviewed
![image](https://user-images.githubusercontent.com/93302874/161845646-a8ce5376-c505-44f7-bfe2-0f34fb0cbba6.png)
- При увеличении текста, картинки неприятно растягиваются. Думаю стоит убрать растягивание картинкам.

![image](https://user-images.githubusercontent.com/93302874/161847114-46cbb2b0-6ae6-4901-baf3-9874c4b3d2ef.png)
- По моему карточки слишком маленькие на таком разрешение.
   - Еще у карточек проблема в том, что они ограничены по высоте, если текста будет больше он начнет выпадать из карточки.
   
   
![image](https://user-images.githubusercontent.com/93302874/161848036-83be2880-ae22-4c92-bea6-647fc11040f7.png)
- Маловат отступ

![image](https://user-images.githubusercontent.com/93302874/161848326-c734a358-4ffc-4be9-bbfc-b9770562cef0.png)
- Картинка не очень хорошо выглядит

2022-04-08 10:21 UTC, closed without merging