Feat/hero
akimoveduard/itmo-landing pull request #28
Opened 2022-04-03 12:12 UTC by rutaizm

2022-04-05 20:05 UTC, StMelik commented on blocks/hero/__container/hero__container.css
> +    padding: 94px 165px 0 864px;
Не нужно так выравнивать внутренний контент!!!

2022-04-05 20:06 UTC, StMelik commented on blocks/hero/__container/hero__container.css
> +.hero__container {
Этот контейнер должен центровать все по центру экрана на любых разрешениях

2022-04-05 20:08 UTC, StMelik commented on index.html
> +      <div class="hero__container">
Оберни содержимое этого контейнера в еще один div, например, с классом hero__content. И прибей его к правой стороне контейнера. И будет счастье =)

2022-04-05 20:10 UTC, StMelik commented on blocks/hero/__title/hero__title.css
> +  font-family: 'Open Sans', Arial, Helvetica, sans-serif;
Наследуется от body

2022-04-05 20:10 UTC, StMelik commented on blocks/hero/__subtitle/hero__subtitle.css
> +    font-family: 'Open Sans', Arial, "Helvetica Neue", Helvetica, sans-serif;
Наследуется от body

2022-04-05 20:12 UTC, StMelik commented on index.html
> +        <button class="hero__button" type="button"><a class="hero__button-link" href=#>Наши проекты</a></button>
Убери <button> оставь только <a>

2022-04-05 20:17 UTC, StMelik requested changes
- Исправить выравнивание блока по центру на больших разрешениях. 
- Попробуй сделать что-то с картинкой, что бы она не обрезалась на больших разрешениях. Если не хочешь заморачиваться, можешь оставить так как есть.

- <i>(Перед внесением изменений запуль ветку, чтобы не было конфликтов)</i>

2022-04-06 07:41 UTC, akimoveduard requested changes

2022-04-06 07:41 UTC, akimoveduard commented on blocks/hero/hero.css
> +    background-position: center;
Я не согласен с выравниваем по центру. Если расширение экрана больше 1440 слева остаются некрасивые "уши". Предлагаю background-position: center left;

2022-04-06 07:41 UTC, akimoveduard commented on blocks/hero/__container/hero__container.css
> +.hero__container {
.hero__container должен иметь ширину 14400px. Он играет роль section__container. Внутри контент нужно выравнивать, поместив его в другой блок, либо каждому из элементов отдав одинаковую геометрию, что, конечно же, неудобно.

2022-04-06 07:41 UTC, akimoveduard commented on blocks/hero/__subtitle/hero__subtitle.css
> +    font-family: 'Open Sans', Arial, "Helvetica Neue", Helvetica, sans-serif;
font-family нужно прописывать только если он сильно отличается от родителя, в данном случае от .page.

2022-04-06 07:41 UTC, akimoveduard commented on blocks/hero/__title/hero__title.css
> +  font-family: 'Open Sans', Arial, Helvetica, sans-serif;
font-family нужно прописывать только если он сильно отличается от родителя, в данном случае от .page.

2022-04-08 10:19 UTC, merged